name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js with Cache
        uses: ./.github/actions/setup-node

      - name: Run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Setup Node.js with Cache
        uses: ./.github/actions/setup-node

      - name: Build package
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Node.js with Cache
        uses: ./.github/actions/setup-node

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: npx semantic-release
